# Tìm hiểu pytorch
---

In [1]:
import torch
import numpy

## 1. Pytorch là gì ?
Trong số những framework hỗ trợ deeplearning thì torch là một trong những framework được ưa chuộng và nó được đông đảo sử dụng. Đây là package sử dụng thư viện của CUDA và C/C++ hỗ trợ các tính toán trên GPU nhằm gia tăng tốc độ xử lý của mô hình. 2 mục đích của package này hướng tới:
- Thay thế kiến trúc của numpy để tính toán trên GPU.
- Deep learning platform cung cấp các xử lý tốc độ và linh hoạt.

## 2. Tensor.

In [2]:
# khởi tạo một ma trận rỗng.
x =torch.empty(5,3)
print(x)

tensor([[3.9719e-23, 1.6143e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
# khởi tạo một ma trận ngẫu nhiên
x = torch.rand(5,3)
x

tensor([[0.6065, 0.2383, 0.9410],
        [0.4205, 0.1823, 0.8542],
        [0.6828, 0.1382, 0.3335],
        [0.7063, 0.8734, 0.0856],
        [0.4479, 0.5940, 0.5152]])

In [4]:
# khởi tạo ma trận 0 với data type là long
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
#khởi tạo ma trận từ list
x = torch.tensor([[5, 3.5]])
x

tensor([[5.0000, 3.5000]])

In [6]:
# khởi tạo ma trận có các thuộc tính tương tự nhưi của một ma trận
# có sẵn. chẳng hạn như kích thước, kiểu dữ liệu, device
# Trừ khi thuộc tính mới được đưa vào ocverride thuộc tính cũ.
x = x.new_ones(5,3, dtype=torch.double) # khởi tạo ma trận 1 với kiểu dữ liệu là double
print(x)
x = torch.randn_like(x, dtype=torch.float) # overrid dtype
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0858,  0.1943,  1.8464],
        [ 0.6417, -0.1277,  1.0480],
        [ 0.4571,  0.9151,  1.2308],
        [ 2.9752,  0.4566,  1.3299],
        [-0.6452,  1.2604, -1.4579]])


### 1.1 Operation

In [7]:
# khởi tạo ngẫu nhiên
x = torch.randn(3,3)
print(x)
y = torch.ones(3,3)
print(x)
print(x+y)

tensor([[ 1.1089, -1.5139,  0.2063],
        [-0.0961,  0.9117, -0.7414],
        [ 0.0754,  2.0140,  0.6414]])
tensor([[ 1.1089, -1.5139,  0.2063],
        [-0.0961,  0.9117, -0.7414],
        [ 0.0754,  2.0140,  0.6414]])
tensor([[ 2.1089, -0.5139,  1.2063],
        [ 0.9039,  1.9117,  0.2586],
        [ 1.0754,  3.0140,  1.6414]])


In [8]:
# Phép cộng
print(torch.add(x,y))
#hoặc cũng có thể đưa kết quả vào một giá trị khởi tạo rỗng.
z = torch.empty(3,3)
torch.add(x,y, out=z)
print(z)
#hoặc
y.add_(x)
print(x)

tensor([[ 2.1089, -0.5139,  1.2063],
        [ 0.9039,  1.9117,  0.2586],
        [ 1.0754,  3.0140,  1.6414]])
tensor([[ 2.1089, -0.5139,  1.2063],
        [ 0.9039,  1.9117,  0.2586],
        [ 1.0754,  3.0140,  1.6414]])
tensor([[ 1.1089, -1.5139,  0.2063],
        [-0.0961,  0.9117, -0.7414],
        [ 0.0754,  2.0140,  0.6414]])


In [9]:
# truy cập index
print(x)
print(x[:, 1]) # => [hàng, cột]

tensor([[ 1.1089, -1.5139,  0.2063],
        [-0.0961,  0.9117, -0.7414],
        [ 0.0754,  2.0140,  0.6414]])
tensor([-1.5139,  0.9117,  2.0140])


In [10]:
#reshape
# để reshape/resize tensor ta sử dụng hàm view.
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 16)
print(z)

tensor([[-1.2604,  1.2891, -0.0896,  0.4234, -0.7397,  0.1710,  0.0842, -1.4699,
          0.3668,  1.5840,  0.3122, -0.1710, -0.4165, -0.7384, -1.7427,  0.8082]])


In [11]:
# Chúng ta có thể chuyển tensor x có 1 phần tử 1 
# numberic python bằng item()
x = torch.tensor([1.5])
x.item()

1.5

## 3. CUDA tensor
là định dạng tensor nhưng được đưa lên device (có thể là cpu, cuda, mkldnn, opengl, ...) hỗ trợ các tính toán nhanh hơn kiến trúc CUDA. Để đưa 1 tensor lên một thiết bị bất kỳ ta sử dụng hàm

In [12]:
# kiểm tra xem có tòn tại CUDA trên máy không.
# lưu ý nếu đang sử dụng google colab, bạn phải bật GPU tại Runtime>change runtime type để enable CUDA.

if torch.cuda.is_available():
    device = torch.device("cuda") # khởi tạo một cude devie object.
    y = torch.ones_like(x, device=device)
    x = x.to(device=device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
    
    

### 3.1 Autograd: Tự động tính đạo hàm.
Trung tâm của toàn bộ các mạng nơ ron hoạt đọng trên pytorch là autograd package.

`Chức năng của autograd`: Tự động tính toán đoaọ hàm trên toàn bộ các toán tử của tensor. Nó là một framework được định nghĩa trong quá trình chạy, có nghĩa rằng quá trình lan  truyền ngược được xác định khi mà code được chạy. và do đó mỗi vogngf lặp có thể có kết quả thay đổi tham số theo lan truyền ngược khác nhau.

`Theo dõi lịch sử của tensor torch`: torch.tensor là package khởi tạo các tensor torch. Mỗi một tensor torch sẽ có 1 thuộc tính là `.requires_grad`, nếu ta sét thuộc tính này về True, các toán tử triển khai trên tensor sẽ được theo dõi. Kgi kết thuốc quá trình lan truyền thuận (hoặc quá trình tính toán output) ta có thể gọi `.backward()` và mọi tính toán gradinent sẽ được tự động thực hiện dựa trên lịch sử đã được lưu lại. các gradient cho tensor này sẽ được tích lũy và xem lại thuộc tính.

Để dừng theo dõi một tensor chúng ta gọi hàm `.detach()` khi đó các hoạt động trên tensor sẽ không còn được lưu vết nữa.

Ngoài ra để ngăn tensor lưu lại lich sử (và sử dụng memory), chúng ta có thể bao quanh code block triển khai tensor với hàm `with torch.no_grad():` nó rất hữu ích trong trường hiowj đánh giá model bởi vì khi thuộc tính `requires_grad = True` thì model sẽ có thể được cập nhật tham số. Nhưng quá trình đánh giá model sẽ không cần cập nhật tham số nên chúng ta cần áp dụng gradient lên chúng. Đơn giản là set `requires_grad = False`.

**Ví dụ về lưu trữ đồ thị tính toán**
Bên dưới ta sẽ khởi tạo một tensor torch có khả năng thay đổi theo 2 cách
- Cách 1: set `requires_grad = True`

In [13]:
import torch
x = torch.ones(2,2,requires_grad=True)
print(x)
y = x+2
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


Do tại x ta thoeo dõi thay đổi bằng các set tham số `requires_grad=True` nên các tính toán được thực hiện trên x sẽ được theo dõi lại ở các thuộc tính `grad_fn`

In [14]:
print(y.grad_fn)

giá trị của `grad_fn` cho thấy ta đã thực hiện một phép cộng để thu được y. thực hiện tiếp 1 biến đổi nữa sử dụng $y$

In [15]:
z = y*y*3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


- Cách 2: theo cách inplace. Mặc định của `requires_grad` khi khởi tạo 1 torch là False tức là sẽ không ghi lại lịch sử thay đổi

In [16]:
a = torch.ones(3, 3)
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b)
print(b.grad_fn)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
False
True
tensor(9., grad_fn=<SumBackward0>)


### 3.2 gradients
thực hiện lan truyền ngược thông qua hàm out.backward()

In [17]:
out.backward()

Kết quả của gradient $d(out)/dx$ sẽ được lưu trong phần từ x.grad

In [18]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


Chúng ta nhận được ma traanjj chỉ gồm các phần tử là 4.5. Đây chính là đạo hàm của mỗi phần tử của x theo $y.\frac{dy}{dx}$

Hàm `torch.autograd` sẽ là hàm chức năng tính tích giữa vector và ma trận jacobian. Hàm số cho ta biết mức độ thay đổi của các chiều khi đi theo phương gradient.

In [19]:
import torch

x = torch.randn(3, requires_grad = True)
yhat = torch.randn(3, requires_grad = True)*2
y = x*2
l = ((y-yhat)**2).mean()
print(l)

tensor(5.6788, grad_fn=<MeanBackward0>)


trong TH này $y$ sẽ không còn là 1 scalar. Hàm `torch.autograd` sẽ không tính toán ma trận jacobian trực tiếp mà thay vào đó sẽ tính tích vector-jacobian theo vector $v$ truyền vào đối số `.backward`

In [20]:
# Khởi tạo một vector gradient tự do v
v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float)
# Tính ma trận Jacobian (đạo hàm của y theo v)
y.backward(v)
# Tính tích vector-jacobian chính là đạo hàm của 
print(x.grad)

tensor([0.2000, 2.0000, 0.0020])


Để dừng autograd theo dõi các thay đổi lịch sử trên tensor, chúng ta có thể thiết lập `.requires_grad=True` hoặc đặt các biến đổi tensor trong block code `torch.no_grad()`.

In [21]:
print(x.requires_grad)
print((x*x).requires_grad)
with torch.no_grad():
  print((x*x).requires_grad)

True
True
False


## Thực hành trên mạng neural network kiến trúc cnn.
Các mạng neural sẽ được xây dựng dựa trên package torch.nn. Dựa trên autograd model sẽ xác định đạo hàm bậc 1 theo các chiều dữ liệu. Một nn.Model sẽ gồm các layers và một phương thức `forward(input)` để trả ra kết quả `output`.

In [22]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(1,6,3)
        self.conv2 = nn.Conv2d(6,16,3)
        self.fc1 = nn.Linear(16*5*5,120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [23]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


chúng ta phải xác định trước `forward` function để trả ra kết quả của model ở đầu ra. Dựa trên `forward` function, hàm `backward` function (là nơi mà gradient tại mỗi layers được tính toán) sẽ được tự đọng sác định khi ta sử dụng `autograd`. Chúng ta cũng có thể sử dụng bất kì một phép biến đổi toán tử Tensor nào trên hàm forward function.

Các tham số huấn luyện (tham số mà có thể thay đổi được trong huấn luyện) của mô hình được  trả về bằng hàm `net.parameters()`

In [24]:
params = list(net.parameters())
print(len(params))
print(f"conv1's weight: {params[0].size()}")

10
conv1's weight: torch.Size([6, 1, 3, 3])


Chúng ta thử nghiệm khởi tạo một đầu vào ngẫu nhiên 32x32. Chú ý rằng: kì vọng đầu vào của mạng lenet là 32x32.

In [25]:
input = torch.randn(1, 1, 28, 28)
out = net(input)
print(out)

tensor([[ 0.0716,  0.1553,  0.0387,  0.0475, -0.0370,  0.0882, -0.0702,  0.1366,
         -0.1700,  0.1398]], grad_fn=<AddmmBackward0>)


khi đó kết quả đầy ra thu được là một tensor có 10 phần tử. mỗi phần tử tương ứng với điểm số được phân bố trong class mà nó thuộc về. Bên dưới chúng ta chuyển toàn bộ các gradients trong bộ nhớ đệm và 0 bằng hàm zero_grad() và lan truyền ngược với gradient ngẫu nhiên.

In [26]:
net.zero_grad()
out.backward(torch.randn(1,10))

**Lưu ý:** `torch.nn` chỉ hỗ trợ các mini-batches. Toàn bộ `torch.nn` packages chỉ hỗ trợ đầu vaofd là mini-batch của mẫu (tức là luôn có 1 chiều trong shape qui định batch size), và không tiếp nhận một mẫu riêng lẽ.

Chẳng hạn, `nn.Conv2d` sẽ nhận đầu vào là 4D Tensor cuẩ nSamples xs nChannel x Height x Width. Trong đó chiều đầu tiên là kích thước mẫu ( batch size).

Nếu bạn có một mẫu đơn lẽ, chỉ cần sử dụng input.unsqueeze(0) để thêm vào một chiều `batch size` giả mạo.

Tổng kết:
- torch.Tensor: là một mảng nhiều chiều hỗ trợ các biến đổi autograd như `backward()`. và cũng lưu trữ các gradients của tensor.
- nn.Module: Neural netword module. Thuận tiện trong gói các tham số với sự hỗ trợ để đẩy chúng lên GPU, export và loading tham số, ...
- autograd.Function: kế thứa quá lan truyền thuận và lan truyền ngược của một biến đổi autograd. Mọi triển khai Tensor tạo ra ít function node kết nối đến function được tạo bởi tensor và mã hóa lịch sử của chúng.

### 1. Hàm Loss
Một hàm loss sẽ nhận 1 cặp (output, target) và tính toán giá trị khoảng cách giữa output và giá trị target.

Có một số dạng loss function khác nhau mà ta có thể tham khảo được hỗ trợ trong nn package: [Loss function trong nn](https://pytorch.org/docs/stable/nn.html#transformer-layers). Dạng đơn giản nhất là `nn.MSELoss` (trung bình bình phương sai số) tính toán trung bình bình phương sai số giữa giá trị output và giá trị target.

In [27]:
output = net(input)
target = torch.randn(10)
target = target.view(1,-1)
criterion = nn.MSELoss()
loss = criterion(output, target)
print(loss)

tensor(0.9986, grad_fn=<MseLossBackward0>)


Tiến trình backward của hàm loss function sẽ sử dụng thuộc tính `.grad_fn` của nó để lần tìm trên đồ thị tính toán quá trình biến đổi tensor như bên dưới:

`input -> conv2d -> relu -> maxpool2d -> conv2d -> relu -> maxpool2d -> view -> linear -> relu -> linear -> relu -> linear -> MSELoss -> loss`

Khi ta gọi và hàm `loss.backward()` toàn bộ graph sẽ tính toán đạo hàm của loss function, các tensors trong graph có thuộc tính `requires_grad = True` thì sẽ có tensor .grad được cập nhật gradient theo trình tự lũy tiến

In [28]:
print(loss.grad_fn) # MSELoss
print(loss.grad_fn.next_functions[0][0]) #Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0]) # Relu

### 2. Lan truyền ngược (backpropagation)
Để lan truyền ngược sử dụng hàm `loss.backward()`. Nhưng trước đó ta cần xóa những gradient đang có và các grandient khác sẽ tích lũy vào gradient hiện có.

In [31]:
net.zero_grad() # chuyển vễ 0 toàn bộ các gradient trong bộ nhớ đẹm của toàn bộ các parameters.
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)
loss.backward()
print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
None
conv1.bias.grad after backward
tensor([-0.0079,  0.0348,  0.0207,  0.0195, -0.0049, -0.0063])


### 3 cập nhật trọng số.
công thức đơn giản để cập nhật trọng số là:

Chúng ta có thể triển khai bằng sử dụng python code đơn giản sau:

In [39]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)
    

trong đó `sub_` là một hàm inplace của phép trừ.
Tuy nhiên khi sử dụng mạng neural networks, ta muốn sử dụng đa dạng các phương pháp cập nhật gradient khác nhau như: SGD, Nesterov-SGD, Adam, RMSProp, ... Do đó sử dụng package `torch.optim` chúng ta có thể thực hiện được toàn bộ những phương pháp gradient descent này một cách đơn giản.

In [40]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
# in your optimizer
optimizer.zero_grad() # Zero gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step() # thực hiện update.

Hàm `criterition()` được sử dụng để tính loss function. `loss.backward()` sẽ thực thiện quá trình lan truyền ngược và `optimizer.step()`.



# Tài liệu tham khảo:

[Buổi 1 - Làm quen với pytorch](https://phamdinhkhanh.github.io/2019/08/10/PytorchTurtorial1.html)



---
$$
end
$$
Rồi ta đã gần như đã học được cách để làm việc với mạng cnn bằng cách sử dụng ta sẽ ứng dụng bạn có thể qua phần đồ án của mình để tham khảo nha ^.^